= Paneron registry kit

A common case of structured data is _registers_, as defined by ISO 19135-1 standard.

Registry kit defines a model for expressing ISO 19135-1 register data as a collection of YAML files,
and simplifies creating Paneron extensions that work with that data.

== Extension development

See ExtensionKit’s documentation for general extension development notes.

== Extensions for editing registry data

An extension is essentially a React component that is given as props
some functions that simplify interaction with underlying data repository.

In case of registry type extensions, instead of writing your own repository view component from scratch,
with the registry kit you can import its registry view component
and pass it a configuration of register item classes that your register supports
alongside props passed by Paneron to your extension.

The configuration of register item classes includes the following:

- General item metadata
-- Machine-readable class identifier, which will also serve as the name of the directory item contents reside in
-- Human-readable item class title, as well as alternative names (if any)
-- Item class description, as plain string
- Default values for register item data
- React components that serve as views of a given register item
-- Displaying item data
-- Editing item data
-- Displaying item in list

For an example of a Paneron extension built with registry kit, see the
link:https://github.com/paneron/extension-geodetic-registry/[ISO/TC 211 Geodetic registry extension].
