name: test

on:
  workflow_call:
  workflow_dispatch:

env:
  # Disable git hooks
  HUSKY: 0

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node:
          - ${{ vars.PANERON_DEFAULT_NODE_VERSION }}
          - '20.x'
          - '22.x'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Has to be run before actions/setup-node.
      # See: https://github.com/actions/setup-node/issues/480
      - name: Enable corepack for yarn
        run: corepack enable

      - name: Install Nodejs
        uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile --immutable

      - name: Run tests
        run: |
          echo Would run: yarn run test
